### ISSUE TITLE
Option to avoid exporting templates

### ISSUE THREAD

**Issue by Zulu-Inuoe** [mmontone/ten#2]
Perhaps it goes against the design of `ten`, but I don't like that template functions are automatically exported from whatever package is designated via `:package`. For one thing, it makes it so that `defpackage` complains about missing exports, and for another, it prevents (except via dirty `unexport` tricks) having internal symbols which you might want in a template group for eg helper templates meant for internal inheritance or some such.

**Comment by mmontone** [comment]
I've implemented an :export boolean option to control whether to export the template or not. The template is exported by default, so you would have to have `:export nil` in your templates. 

Would that be good enough?

**Comment by Zulu-Inuoe** [comment]
Yeah. That seems reasonable. I'm only beginning experimenting with ten, so I more wanted to open conversation.
Thanks!
