### ISSUE TITLE
Feature request: Comments inside template

### ISSUE THREAD

**Issue by wnortje** [mmontone/ten#5]
Hi

It would be useful if it was possible to comment out parts of a template. Maybe like Jinja does using `{#` and `#}`.

**Comment by mmontone** [comment]
Hi @wnortje , I'll have a look at your requests ..

**Comment by mmontone** [comment]
> Maybe like Jinja does using `{#` and `#}`.

I implemented it like that.

**Comment by wnortje** [comment]
Thanks very much.

Your response time is incredible.

**Comment by lispstudent** [comment]
Thank you, nice addition!

Perhaps the initial section of [Readme](https://github.com/mmontone/ten/blob/21dab90c965240291ad9f169e837e70b08843c5e/README.md?plain=1#L12) could be updated?

> Two types of tags only. Control and output.
